
# Shared across all profiles
spring:
  application:
    name: seal-registry-service #name of the application
  cloud:
    config:
      fail-fast: true #the service will not run if it can't reach the config-service
      password: 1234 #password of the config-service
      username: user #username of the config-service
      retry:
        initial-interval: 5000
        max-attempts: 1

---

# Local profile
spring:
  config:
    import: optional:configserver:http://localhost:7777
    activate:
      on-profile: local


---

# test profile
spring:
  cloud:
    config:
      uri: http://192.168.8.100:8888
  config:
    activate:
      on-profile: test

---

# Dev profile
spring:
  cloud:
    config:
      uri: http://config-service-prod.default.svc.cluster.local:8080/config-service
  config:
    activate:
      on-profile: dev